[profile.default]
solc_version = "0.8.24"
evm_version = "shanghai"

remappings = [
  "drips-contracts/=lib/drips/src",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts",
]

[fmt]
line_length = 100

[profile.release]
optimizer = true
via_ir = true
optimizer_runs = 4294967295
